MGatewayBO/Controllers/MerchantSetupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Global.Model;
using MGatewayHelpers;
using MGatewayProcessor;
using MGatewayBO.Model;
namespace MGatewayBO.Controllers
{
    public class MerchantSetupController : Controller
    {
      
        public ActionResult Index()
        {
            ViewBag.ObjectID = 7;
            ViewBag.Title = "Merchant Setup";
            return ReloadMerchantList();
        }

        public ActionResult ReloadMerchantList()
        {
            JsGridModel m = PrepareMerchantList();
            return View(m);
        }

        private JsGridModel PrepareMerchantList()
        {
            JsGridModel m = MerchantSetup.GetMerchantGrid();
            GridControllerHelper.UpdateRouteURL(m, Request.RequestContext);
            return m;
        }

        public ActionResult UpdateMerchant(MerchantDataModel vm)
        {
            MerchantDataModel m = MerchantSetup.UpdateMerchantDetails(vm);
            return Json(m);
        }

        public ActionResult DeleteMerchant(MerchantDataModel vm)
        {
            MerchantSetup.DeleteMerchant(vm);
            return Json(true);
        }


        public ActionResult ViewMerchantDetails(MerchantDataViewModel vm)
        {
           
            return PartialView("_EditForm", vm);
        }




    }
}

MGatewayBO/Views/MerchantSetup/Index.cshtml
@model Global.Model.JsGridModel
@{


}
<body>

    <div class="container-fluid">

        <div class="card" id="MerchantSetupfrm">


            <div class="col-xs-12 section-header">Merchant Setup</div>

            <div class="card-body col-sm-12 p-2" id="parentElement">
                <div class="form-group col-12">
                    <div class="text-left">
                        <div class="hr10 visible-xs"></div>
                        <button type="button" id="btnAddMerchant" class="btn btn-primary">Create Merchant</button>
                        <div class="hr10 visible-xs"></div>
                    </div>
                </div>
                <div id="gdvMerchant"></div>

            </div>

            <div class="card-body col-sm-12 p-2" id="chilElement" style="display:none">

                <div id="MerchantDetails"></div>

                <div class="form-group col-sm-12">
                    <div class="text-center">
                        <div class="hr10 visible-xs"></div>
                        <button type="button" id="btnBack" class="btn btn-primary">Back</button>
                        <div class="hr10 visible-xs"></div>
                    </div>
                </div>


            </div>

        </div>
    </div>



</body>
<link rel="stylesheet" type="text/css" href="~/Content/BackOffice/Backoffice.css">
<script type="text/javascript">
  var SerializeModel = JSON.parse('@Html.Raw(Json.Encode(Model))');
    var ViewMerchantDetailsURL = '@Url.Action("ViewMerchantDetails", "MerchantSetup", new { Area = "" })'
    var UpdateMerchantURL = '@Url.Action("UpdateMerchant", "MerchantSetup", new { Area = "" })'
    var LoadGatewayIndex = '@Url.Action("Index", "MerchantSetup", new { Area = "" })'
    var AddGatewayMerchantURL = '@Url.Action("AddGatewayMerchant", "MerchantSetup", new { Area = "" })'
    var DeleteGatewayMerchantURL = '@Url.Action("DeleteGatewayMerchant", "MerchantSetup", new { Area = "" })'
    var statusTemplate = function (value) {
                    var backgroundcolor = '#d84d4d'
        if (value == '0') {
                        value = 'Inactive'
            backgroundcolor = '#9795a7'
        } else if (value == '1') {
                        value = 'Active'
            backgroundcolor = '#337b2b'
        }
                    var elem = $('<div>').attr({ style: 'background-color:' + backgroundcolor + ';border-radius: 5px;text-align: center;color: white;font-weight: bold;' }).text(value);
                    //var Statuselem = $("<a>").attr("href", value).text(value);
                    elem.append(elem)

        return elem;
                }
                var customItemTemplate = {

        AccountStatus: statusTemplate
    }


            var CustomPostCallback = function (data) {
        //to handle if populate grid or normal form
        InitDateRangePicker('.txt_daterange');
            InitDatePicker('.txt_date');
            InitNumeric('.txt_num');

        }

    $('#gdvMerchant').IniJsGrid(SerializeModel, customItemTemplate);


    $('#btnBack').click(function (s, e){
            window.location = LoadGatewayIndex;


        })

    $('#btnAddMerchant').click(function (s, e) {

            ViewMerchantDetails(true);
        })



    function ViewMerchantDetails() {

            var _data = {'vm': {}}
        var ajxNew = new _func.ajxNew();

        ajxNew.url = ViewMerchantDetailsURL;
        ajxNew.data = _data;

        _func.ajxCall(ajxNew, function (returndata) {
            var data = returndata.returnVal;
            if (returndata) {
                $('#MerchantDetails').html(data);
                    $('#parentElement').hide();
                    $('#chilElement').show();
        InitDateRangePicker('.txt_daterange');

    };
        });
    }



    $('#chilElement').on('click', '#btnUpdateDetails', function (s, e) {
        var elem = $(this)
        var _data = collectData()
        var ajxNew = new _func.ajxNew();

        ajxNew.url = UpdateMerchantURL;
        ajxNew.data = _data;
        ajxNew.processData = false;
        ajxNew.contentType = false;

        if (Validate('#MerchantSetupfrm')) {
            _func.ajxCall(ajxNew, function (returndata) {
                var data = returndata.returnVal;
                
                    if (elem.text() == 'Add') {
                        showMessage('Add Successfully!', true);
                        elem.text("Update");
                        $('#GatewayMerchanfrm').show();
                    } else {
                        showMessage('Update Successfully!', true);
                }
                $('#chilElement').find('#APIKEY').val(data.APIKEY);
                

                    //$('#gdvUsers').IniJsGrid(data, customItemTemplate);


                
            });
        }




    });

    $('#chilElement').on('click', '#btnAddPaymentGateway', function (s, e) {

        if ($('#GatewayID').val() != '') {
            var _data = { 'MerchantID': $('#merchantID').val(), 'GatewayID': $('#GatewayID').val() }
            var ajxNew = new _func.ajxNew();


            ajxNew.url = AddGatewayMerchantURL;
            ajxNew.data = _data;

            _func.ajxCall(ajxNew, function (returndata) {
                var data = returndata.returnVal;
                if (data != '') {
                    var tr = $('<tr data-serviceid="' + data + '">');
                    var td = $('<td>');
                    td.html('<input class="tableDeleteIcon" />')
                    tr.append(td);

                    td = $('<td>');
                    td.html(data)
                    tr.append(td);

                    td = $('<td>');
                    td.html($('#GatewayID').val());
                    tr.append(td);

                    td = $('<td>');
                    td.html($('#GatewayID :Selected').text());
                    tr.append(td);

                    $('#tblGatewayMerchant tbody').append(tr);
                    tr.append(td);

                } else {
                    showMessage('Duplicate Record!', false);
                };
            })
            } else {
            showMessage('Please Select Payment Gateway', false);
         }
   
    });

    $('#chilElement').on('click', '.tableDeleteIcon', function (s, e) {
        var tr = $(this).closest('tr');
        var serviceId = tr.data('serviceid');
        var _data = { 'ServiceID': serviceId }
        var ajxNew = new _func.ajxNew();


        ajxNew.url = DeleteGatewayMerchantURL;
        ajxNew.data = _data;

        _func.ajxCall(ajxNew, function (returndata) {
            var data = returndata.returnVal;
            if (returndata != '') {

                showMessage('Record Deleted!', true);
                tr.remove();
            } else {
                
            };
        });
    });

    function collectData() {
        var fd = new FormData();
        fd.append('merchantID', $('#chilElement').find('#merchantID').val())
        fd.append('merchantName', $('#chilElement').find('#merchantName').val())
        fd.append('APIKEY', $('#chilElement').find('#APIKEY').val())
        fd.append('success_url', $('#chilElement').find('#success_url').val())
        fd.append('cancel_url', $('#chilElement').find('#cancel_url').val())
        fd.append('fail_url', $('#chilElement').find('#fail_url').val())
        fd.append('merchantStatus', ($('#chilElement').find('#merchantStatus').is(":checked") ? 1 : 0))
        return fd;
    }







</script>

MGatewayBO/Views/MerchantSetup/_EditForm.cshtml
@model MGatewayBO.Model.MerchantDataViewModel
@{
    bool isUpdate = (Model.merchantID != null ? true : false);
    ReportPortal.Helper.FormHelper formHelper = new ReportPortal.Helper.FormHelper(Html, ViewContext);
}

<div class="container-fluid">
    
    <div class="form-group col-sm-12 mt-1 ">

        @formHelper.AddTextBox(null, "merchantID", "Merchant ID", !isUpdate, !isUpdate)
        @formHelper.AddTextBox(null, "merchantName", "Merchant Name", true, true)
        @formHelper.AddTextBox(null, "APIKEY", "API Key", false,false)

        @formHelper.AddToggleBox(Model.merchantStatus, "merchantStatus", "Merchant Status", true)


    </div>
   
    <div class="form-group col-12">
        <div class="text-center">
            <div class="hr10 visible-xs"></div>
            <button type="submit" id="btnUpdateDetails" class="btn btn-primary">@(isUpdate ? "Update": "Add")</button>
            <div class="hr10 visible-xs"></div>
        </div>
    </div>
</div>