MGatewayBO/Controllers/CashTransactionLogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Global.Model;
using MGatewayHelpers;
using MGatewayProcessor;
using MGatewayBO.Model;
using System.Data;
namespace MGatewayBO.Controllers
{
    public class CashTransactionLogController : Controller
    {
      
        public ActionResult Index(string _TrxType)
        {
            ViewBag.Title = "Cash In Out Log";
            ViewBag.ObjectID = 11;
          
            DateTime currentMonth = DateTime.Today;
            DateTime StartDate = new DateTime(currentMonth.Year, currentMonth.Month, 1);
            DateTime EndDate = new DateTime(currentMonth.Year, currentMonth.Month, DateTime.DaysInMonth(currentMonth.Year, currentMonth.Month));
            string _StartDate = StartDate.ToString(GlobalProperties.gDisplayDateFormat);
            string _EndDate = EndDate.ToString(GlobalProperties.gDisplayDateFormat);

            return ReloadTransactionList( _StartDate, _EndDate);
        }

        public ActionResult ReloadTransactionList(string _StartDate, string _EndDate)
        {
            JsGridModel m = PrepareTransactionList(_StartDate, _EndDate);
           
            List<CashInOutLogViewModel> dataList = CashTransactionLog.GetTransactionInfoCache(GlobalProperties.UserID);
            ViewBag.TotalAmount = CashTransactionLog.GetTransactionTotalAmount(dataList);
            ViewBag.DateRange = _StartDate + " - " + _EndDate;
           
            PrepareEditFormViewBag();
            List<SelectListItem> selectlist = new List<SelectListItem>();
            List<ShopModel> ShopList = Shop.GetShop(GlobalProperties.MerchantID);
            foreach (ShopModel item in ShopList)
            {
                selectlist.Add(new SelectListItem { Value = item.ShopID, Text = item.ShopName });
            }
            ViewBag.ShopList = selectlist;


            return View(m);
        }

        public ActionResult ReloadTransactionListDate(string _StartDate, string _EndDate, List<string> ShopList)
        {
            TrxInfoGridReloadResult trxInfoGridReloadResult = new TrxInfoGridReloadResult();
            JsGridModel m = PrepareTransactionList(_StartDate, _EndDate);
            List<CashInOutLogViewModel> dataList = CashTransactionLog.GetTransactionInfoCache(GlobalProperties.UserID);
            if (ShopList != null)
            {
                List<CashInOutLogViewModel> NewdataList = new List<CashInOutLogViewModel>();
                foreach (CashInOutLogViewModel item in dataList)
                {
                    if (ShopList.Contains(item.ShopID))
                    {
                        NewdataList.Add(item);
                    }
                }
                m.data = NewdataList;
                CashTransactionLog.UpdateTransactionInfoCache(GlobalProperties.UserID, NewdataList);
               
            }

            trxInfoGridReloadResult.jsGrid = m;
            trxInfoGridReloadResult.TotalAmount = CashTransactionLog.GetTransactionTotalAmount(dataList);


            return Json(trxInfoGridReloadResult);
        }

        private JsGridModel PrepareTransactionList(string _StartDate, string _EndDate)
        {
           
            JsGridModel m = CashTransactionLog.GetCashTransactionGrid(GlobalProperties.UserRole, GlobalProperties.MerchantID,GlobalProperties.UserID, _StartDate, _EndDate);
            GridControllerHelper.UpdateRouteURL(m, Request.RequestContext);
            return m;
        }

        public ActionResult LoadCashTransaction(CashInOutLogViewModel vm,int pageIndex, int pageSize, string sortField, string sortOrder)
        {

            CashTransactionGridLogFilterResult resultData = CashTransactionLog.PerformFilter(GlobalProperties.UserID,vm, pageIndex, pageSize, sortField, sortOrder);
            

            return Json(resultData);
        }


        public ActionResult ExportToExcel(string ExportProvider)
        {
            List<CashInOutLogViewModel> trxModel = CashTransactionLog.GetTransactionInfoCache(GlobalProperties.UserID);

            byte[] sfilebytes = Function.ExportToExcelCollection<CashInOutLogViewModel>(trxModel);
            string sfilename = "TransactionLog_" + DateTime.Today.ToString("dd_mm_yyyy") + ".xlsx";
            string filetype = "application/vnd.ms-excel";

            return File(sfilebytes, filetype, sfilename);
        }


        private void PrepareEditFormViewBag()
        {
            List<SelectListItem> selectlist = new List<SelectListItem>();
            Dictionary<int, string> TransactionTypeDict = MGatewayProcessor.Helpers.DataReaderHelper.GetEnumDict(typeof(TransactionType));

            
            foreach (KeyValuePair<int, string> item in TransactionTypeDict)
            {
                selectlist.Add(new SelectListItem { Value = item.Key.ToString(), Text = item.Value });
            }
            ViewBag.TransactionTypeList = selectlist;

            selectlist = new List<SelectListItem>();
            Dictionary<int, string> WalletTypeDict = MGatewayProcessor.Helpers.DataReaderHelper.GetEnumDict(typeof(WalletType));

            
            foreach (KeyValuePair<int, string> item in WalletTypeDict)
            {
                selectlist.Add(new SelectListItem { Value = item.Key.ToString(), Text = item.Value });
            }
            ViewBag.WalletTypeList = selectlist;

        }








    }
}

MGatewayBO/Views/CashTransactionLog/Index.cshtml
@model Global.Model.JsGridModel
@{

    ReportPortal.Helper.FormHelper formHelper = new ReportPortal.Helper.FormHelper(Html, ViewContext);
   
}
<head>
    <style>
        .external-pager {
            margin: 10px 0;
        }

            .external-pager .jsgrid-pager-current-page {
                background: #c4e2ff;
                color: #fff;
            }

            .external-pager .jsgrid-pager {
                padding-left: 10px;
            }
    </style>
</head>
<body>

    <div class="container-fluid">

        <div class="card">


            <div class="col-xs-12 section-header">@ViewBag.Title  </div>
            @formHelper.AddDateRangeTextBox(ViewBag.DateRange, "DateRange", "Select Period", true, false)
            @formHelper.AddMultiSelectDropDown("", "ShopName", "Shop Name", ViewBag.ShopList, true, true)


            <div class="card-body col-sm-12 p-2" id="parentElement">

                <div class="form-group col-12">
                    <div class="text-left">
                        <div class="hr10 visible-xs"></div>
                        @*<button type="button" id="btnAddRecord" class="btn btn-primary" data-toggle="modal" data-target="#AddRecordModal">Add</button>*@

                        <button type="button" id="btnExport" class="btn btn-primary">Export</button>
                        <div class="hr10 visible-xs"></div>
                    </div>
                </div>
                <div id="gdvTransaction"></div>
                <div id="externalPager" class="external-pager"></div>
                <div id="gdvTransactionFooter" class="external-pager jsgrid-pager-container" style="">
                    <div class="jsgrid-pager" style="background-color: #99d532;color:black ">
                        <span style="font-weight: bold; margin-right: 10px; ">Total Amount :</span>
                        <span style=" margin-right: 20px;" id="footertotalAmount">  @ViewBag.TotalAmount </span>
                        <span style="font-weight: bold; margin-right: 10px;">Filterd Total Amount :</span>
                        <span id="footerfilteredamount"> @ViewBag.TotalAmount </span>

                    </div>
                </div>
            </div>

            <div class="card-body col-sm-12 p-2" id="chilElement" style="display:none">

                <div id="TransactionDetails"></div>

                <div class="form-group col-sm-12">
                    <div class="text-center">
                        <div class="hr10 visible-xs"></div>
                        <button type="button" id="btnBack" class="btn btn-primary">Back</button>
                        <div class="hr10 visible-xs"></div>
                    </div>
                </div>


            </div>

        </div>
    </div>


    @*<div class="modal fade" id="AddRecordModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content" style="background-color:white;">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Add New Transaction</h5>
                    <button type="button" class="btn-close" style="background-color:black;" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="form-group col-sm-12 mt-1 ">
                        @formHelper.AddComboBox(null, "TransactionType", "Transaction Type", ViewBag.TransactionTypeList, true, true)
                        @formHelper.AddComboBox(null, "WalletType", "Gateway", ViewBag.WalletTypeList, true, true)
                        @formHelper.AddTextBox(null, "MemberPhoneNo", "Sender Number", true, true)
                        @formHelper.AddNumericBox(null, "Amount", "Send Amount", true, true)
                        @formHelper.AddTextBox(null, "TrxID", "TransactionID", true, true)

                    </div>


                </div>
                <div class="modal-footer">

                    <div class="form-group col-12">
                        <div class="text-center">
                            <div class="hr10 visible-xs"></div>
                            <button type="submit" id="btnUpdateDetails" class="btn btn-primary">Submit</button>
                            <div class="hr10 visible-xs"></div>
                        </div>
                    </div>



                </div>
            </div>
        </div>
    </div>*@


    <div class="modal fade" id="ApprovedModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content" style="background-color:white">
                <div class="modal-header" style="border-bottom: 1px solid #d7d3d3">
                    <h5 class="modal-title" id="exampleModalLabel">Transaction ID</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                      
                    </button>
                </div>
                <span id="modalerrorMsg" style="color: red; font-weight: bold; display: none; padding-left: 50px; padding-top: 10px;">Please key in Transaction ID</span>
                <div class="modal-body" style="border-bottom: 1px solid #d7d3d3">
                    @formHelper.AddTextBox(null, "TrxID", "TransactionID", true, true)
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-primary" data-bs-dismiss="modal">Close</button>
                    <button type="button" id="btnModalApprove" class="btn btn-primary">Approve</button>
                </div>
            </div>
        </div>
    </div>


    <div class="modal fade" id="AddRecordModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
            </div>
        </div>
    </div>


</body>
<link rel="stylesheet" type="text/css" href="~/Content/BackOffice/Backoffice.css">
<script type="text/javascript">
    var SerializeModel = JSON.parse('@Html.Raw(Json.Encode(Model))');
 
    var ReloadTransactionListURL = '@Url.Action("ReloadTransactionListDate", "CashTransactionLog", new { Area = "" })'
 
    var ExportToExcelURL = '@Url.Action("ExportToExcel", "CashTransactionLog", new { Area = "" })'

    var statusTemplate = function (value) {
        var backgroundcolor = '#d84d4d'
        if (value == 'Success' || value =='Verified') {

            backgroundcolor = '#3a8e5c'
        } else if (value == 'Pending') {

            backgroundcolor = '#389688'
        } else if (value == 'New') {
            backgroundcolor = '#f5c02f'
        } else if (value == 'Failed') {
            backgroundcolor = '#b71c1c'
        } else if (value == 'Cancelled') {
            backgroundcolor = '#b71c1c'
        } else if (value == 'Manual') {
            backgroundcolor = '#ef6c00'
        } else if (value == 'Expired') {
            backgroundcolor = '#b71c1c'
        } else if (value == 'UpdateSuccess') {
            backgroundcolor = '#3a8e5c'
        } else if (value == 'UpdateFailed') {
            backgroundcolor = '#b71c1c'
        }
                    var elem = $('<div>').attr({ style: 'background-color:' + backgroundcolor + ';border-radius: 5px;text-align: center;color: white;font-weight: bold;' }).text(value);
                    //var Statuselem = $("<a>").attr("href", value).text(value);
                    elem.append(elem)

        return elem;
    }


    var ActionTemplate = function (value,item) {

        var elem = '<button type="button" id="btnAction" data-id="' + item.ID + '" data-trxid="' + item.TrxID + '" class="btn btn-primary" style="padding: 5px;padding-left: 10px;padding-right: 10px;font-size: small;">Approve</button>'
        elem += '<button type="button" id="btnReject" data-id="' + item.ID + '" data-trxid="' + item.TrxID + '" class="btn btn-primary" style="padding: 5px;padding-left: 10px;padding-right: 10px;font-size: small;">Reject</button>'
        //var Statuselem = $("<a>").attr("href", value).text(value);
       // elem.append(elem)
        if (item.Status == 'Approved' || item.Status == 'Rejected') {
            elem = ''
        } ;
        return elem;
    }

    var buttonTemplate = function (value) {
        if (value == '') {
            return $('<div>');
        } else {
            var elem = $('<div>').click(function (e) {
                showMessage('Successfully Copied!', true);
                var $temp = $("<input>");
                $("body").append($temp);
                $temp.val($(this).closest('td').text()).select();
                document.execCommand("copy");
                $temp.remove();



            })
            var buttonelem = $("<button>").attr({ title: 'Click here to copy Token', class: "fa fa-clone", 'aria-hidden': "true", style: 'background: transparent;border: none;' })
            elem.append(value);
            elem.append(buttonelem)
            return elem;
        }


    }


     var customItemTemplate = {

         Action: ActionTemplate,
         TrxStatus: statusTemplate,
         TrxID: buttonTemplate,
         TrxID_G: buttonTemplate,
         TrxID_M: buttonTemplate,
    }


    var CustomPostCallback = function (data) {

       // ReloadTransaction($('#DateRange').data('daterangepicker').startDate.format('DD/MM/YYYY'), $('#DateRange').data('daterangepicker').endDate.format('DD/MM/YYYY'), $('#ShopName').val());


        //to handle if populate grid or normal form
        //InitDateRangePicker('.txt_daterange');
        //    InitDatePicker('.txt_date');
        //    InitNumeric('.txt_num');

    }

    var CustomFilterCallback = function (data) {
        $('#footerfilteredamount').html(data.FilterAmount);
    }

    $('#gdvTransaction').IniJsGrid(SerializeModel, customItemTemplate);



    $('#DateRange').on('apply.daterangepicker', function (ev, picker) {

        ReloadTransaction(picker.startDate.format('DD/MM/YYYY'), picker.endDate.format('DD/MM/YYYY'), $('#ShopName').val());


       // $(this).val(picker.startDate.format('DD/MM/YYYY') + ' - ' + picker.endDate.format('DD/MM/YYYY'));

    });


    $('#ShopName').on('change', function (e) {
        ReloadTransaction($('#DateRange').data('daterangepicker').startDate.format('DD/MM/YYYY'), $('#DateRange').data('daterangepicker').endDate.format('DD/MM/YYYY'), $('#ShopName').val());
    })
   

    $('#btnExport').click(function (e) {
        window.location.href = ExportToExcelURL + '?ExportProvider=1';
    })

    function ReloadTransaction(startDate,endDate, shopList) {

        var _data = {  '_StartDate': startDate, '_EndDate': endDate, 'ShopList': shopList  }
        var ajxNew = new _func.ajxNew();

        ajxNew.url = ReloadTransactionListURL;
        ajxNew.data = _data;

        _func.ajxCall(ajxNew, function (returndata) {
            var data = returndata.returnVal;
            if (returndata) {
                $('#gdvTransaction').IniJsGrid(data.jsGrid, customItemTemplate);
                $('#footertotalAmount').html(data.TotalAmount);
                $('#footerfilteredamount').html(data.TotalAmount);
            };
        });
    }


</script>