MGatewayBO/Controllers/PaymentGatewaySetupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Global.Model;
using MGatewayHelpers;
using MGatewayProcessor;
using MGatewayBO.Model;
namespace MGatewayBO.Controllers
{
    public class PaymentGatewaySetupController : Controller
    {
      
        public ActionResult Index()
        {
            ViewBag.Title = "Payment Gateway Setup";
            return ReloadGatewayList();
        }

        public ActionResult ReloadGatewayList()
        {
            JsGridModel m = PrepareGatewayList();
            return View(m);
        }

        private JsGridModel PrepareGatewayList()
        {
            JsGridModel m = PaymentGatewaySetup.GetPaymentGatewayGrid();
            GridControllerHelper.UpdateRouteURL(m, Request.RequestContext);
            return m;
        }

        public ActionResult UpdateGateway(GatewayDataModel vm)
        {
            PaymentGatewaySetup.UpdateGatewayDetails(vm);
            return Json(true);
        }

        public ActionResult DeleteGateway(GatewayDataModel vm)
        {
            PaymentGatewaySetup.DeleteGateway(vm);
            return Json(true);
        }


        public ActionResult ViewGatewayDetails(GatewayDataModel vm)
        {
            return PartialView("_EditForm", vm);
        }



    }
}

MGatewayBO/Views/PaymentGatewaySetup/Index.cshtml
@model Global.Model.JsGridModel
@{


}
<body>

    <div class="container">

        <div class="card">


            <div class="card-header mb-1 bluebg">
                <h3 class="card-title bolder">Payment Gateway</h3>
                <div class="card-tools">
                    <button type="button" class="btn btn-tool" data-card-widget="collapse">
                        @*<i class="fas fa-minus"></i>*@
                    </button>

                </div>
            </div>

            <div class="card-body col-sm-12 p-2" id="parentElement">
                <div class="form-group col-12">
                    <div class="text-left">
                        <div class="hr10 visible-xs"></div>
                        <button type="button" id="btnAddGateway" class="btn btn-primary">Create Gateway</button>
                        <div class="hr10 visible-xs"></div>
                    </div>
                </div>
                <div id="gdvGateway"></div>

            </div>

            <div class="card-body col-sm-12 p-2" id="chilElement" style="display:none">

                <div id="PaymentGatewayDetails"></div>

                <div class="form-group col-sm-12">
                    <div class="text-center">
                        <div class="hr10 visible-xs"></div>
                        <button type="button" id="btnBack" class="btn btn-primary">Back</button>
                        <div class="hr10 visible-xs"></div>
                    </div>
                </div>


            </div>

        </div>
    </div>



</body>
<link rel="stylesheet" type="text/css" href="~/Content/BackOffice/Backoffice.css">
<script type="text/javascript">
  var SerializeModel = JSON.parse('@Html.Raw(Json.Encode(Model))');
    var ViewGatewayDetailsURL = '@Url.Action("ViewGatewayDetails", "PaymentGatewaySetup", new { Area = "" })'
    var UpdateGatewayURL = '@Url.Action("UpdateGateway", "PaymentGatewaySetup", new { Area = "" })'
    var ReloadGatewayListURL = '@Url.Action("ReloadGatewayList", "PaymentGatewaySetup", new { Area = "" })'
    var LoadGatewayIndex = '@Url.Action("Index", "PaymentGatewaySetup", new { Area = "" })'
    var statusTemplate = function (value) {
        var backgroundcolor = '#d84d4d'
        if (value == '0') {
            value = 'Inactive'
            backgroundcolor = '#9795a7'
        } else if (value == '1') {
            value = 'Active'
            backgroundcolor = '#337b2b'
        }
        var elem = $('<div>').attr({ style: 'background-color:' + backgroundcolor + ';border-radius: 5px;text-align: center;color: white;font-weight: bold;' }).text(value);
        //var Statuselem = $("<a>").attr("href", value).text(value);
        elem.append(elem)

        return elem;
    }
    var customItemTemplate = {

        AccountStatus: statusTemplate
    }


    var CustomPostCallback = function (data) {
        //to handle if populate grid or normal form
        InitDateRangePicker('.txt_daterange');
        InitDatePicker('.txt_date');
        InitNumeric('.txt_num');

    }

    $('#gdvGateway').IniJsGrid(SerializeModel, customItemTemplate);


    $('#btnBack').click(function (s, e){
        window.location = LoadGatewayIndex;


    })

    $('#btnAddGateway').click(function (s, e) {

        ViewGatewayDetails(true);
    })

    function ReloadGatewayList() {
        var _data = { 'vm': {} }
        var ajxNew = new _func.ajxNew();

        ajxNew.url = ReloadGatewayListURL;
        ajxNew.data = _data;

        _func.ajxCall(ajxNew, function (returndata) {
            var data = returndata.returnVal;
            if (returndata) {
                $('#gdvGateway').IniJsGrid(data, customItemTemplate);

            };
        });
    }

    function ViewGatewayDetails() {

        var _data = {'vm': {}}
        var ajxNew = new _func.ajxNew();

        ajxNew.url = ViewGatewayDetailsURL;
        ajxNew.data = _data;

        _func.ajxCall(ajxNew, function (returndata) {
            var data = returndata.returnVal;
            if (returndata) {
                $('#PaymentGatewayDetails').html(data);
                    $('#parentElement').hide();
                    $('#chilElement').show();
                InitDateRangePicker('.txt_daterange');

            };
        });
    }



    $('#chilElement').on('click', '#btnUpdateDetails', function (s, e) {
        var elem = $(this)
        var _data = collectData()
        var ajxNew = new _func.ajxNew();

        ajxNew.url = UpdateGatewayURL;
        ajxNew.data = _data;
        ajxNew.processData = false;
        ajxNew.contentType = false;

        if (Validate('.container')) {
            _func.ajxCall(ajxNew, function (returndata) {
                var data = returndata.returnVal;
                if (returndata) {
                    if (elem.text() == 'Add') {
                        showMessage('Add Successfully!', true);
                        elem.text("Update");
                    } else {
                        showMessage('Update Successfully!', true);
                    }


                };
            });
        }




    })

    function collectData() {
        var fd = new FormData();
        fd.append('GatewayID', $('#chilElement').find('#GatewayID').val())
        fd.append('GatewayKey', $('#chilElement').find('#GatewayKey').val())
        fd.append('GatewayName', $('#chilElement').find('#GatewayName').val())
        fd.append('GatewayEmail', $('#chilElement').find('#GatewayEmail').val())
  
        return fd;
    }







</script>

MGatewayBO/Views/PaymentGatewaySetup/_EditForm.cshtml
@model MGatewayBO.Model.GatewayDataModel
@{
    bool isUpdate = (Model.GatewayID != null ? true : false);
    ReportPortal.Helper.FormHelper formHelper = new ReportPortal.Helper.FormHelper(Html, ViewContext);
}

<div class="container">
    <div class="col-xs-12 section-header">Gateway Setup</div>

    <div class="form-group col-sm-12 mt-1 ">
     
        @formHelper.AddTextBox(null, "GatewayID", "Gateway ID", !isUpdate, !isUpdate)
        @formHelper.AddTextBox(null, "GatewayKey", "Gateway Key", true, true)
        @formHelper.AddTextBox(null, "GatewayName", "Gateway Name", true, true)
        @formHelper.AddTextBox(null, "GatewayEmail", "Gateway Email", true, true)
     

    </div>

    <div class="form-group col-12">
        <div class="text-center">
            <div class="hr10 visible-xs"></div>
            <button type="submit" id="btnUpdateDetails" class="btn btn-primary">@(isUpdate ? "Update": "Add")</button>
            <div class="hr10 visible-xs"></div>
        </div>
    </div>
</div>