MGatewayBO/Controllers/GlobalSettingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MGatewayBO.Controllers
{
    public class GlobalSettingsController : Controller
    {
      
        public ActionResult Index()
        {
            ViewBag.Title = "Global Settings";
            ViewBag.ObjectID = 8;
            Model.GlobalSetingsViewModel m = MGatewayProcessor.GlobalSettings.GetSettings();
            Dictionary<int, string> WalletType = MGatewayProcessor.Helpers.DataReaderHelper.GetEnumDict(typeof(Model.WalletType));
            Dictionary<string, Model.ShopWalletsSenderModel> ShopwalletSenderDict = MGatewayProcessor.Shop.GetShopWalletSender();
            Dictionary<string, Model.RejectRemarksModel> RejectRemarksDict = MGatewayProcessor.GlobalSettings.GetRejectRemarksDict();
            ViewBag.WalletTypeDict = WalletType;
            ViewBag.WalletSender = ShopwalletSenderDict;
            ViewBag.RejectRemark = RejectRemarksDict;
            return View(m);
        }

        public ActionResult UpdateSettings(Model.GlobalSetingsViewModel vm, List<Model.ShopWalletsSenderModel> WalletSenderList, List<Model.RejectRemarksModel> RejectRemarksList)
        {
            MGatewayProcessor.GlobalSettings.UpdateSettings(vm);
            MGatewayProcessor.GlobalSettings.UpdateRejectRemark(RejectRemarksList);
            MGatewayProcessor.Shop.UpdateShopWalletSender(WalletSenderList);

            return Json(true);
        }

        public ActionResult DeleteRejectRemark(string ID)
        {
          
            MGatewayProcessor.GlobalSettings.DeleteRejectRemark(ID);
            

            return Json(true);
        }



    }
}

MGatewayBO/Views/GlobalSettings/Index.cshtml
@model MGatewayBO.Model.GlobalSetingsViewModel
@{
    Dictionary<string, MGatewayBO.Model.ShopWalletsSenderModel> ShopwalletSenderDict = ViewBag.WalletSender;
    Dictionary<int, string> WalletType = ViewBag.WalletTypeDict;
    ReportPortal.Helper.FormHelper formHelper = new ReportPortal.Helper.FormHelper(Html, ViewContext);
}


<div class="container-fluid">

    <div class="col-xs-12 section-header">Global Settings</div>
    <div class="form-group col-sm-12 mt-1 ">

        <label>App download link : https://www.genkinpay.com/Handler/File.ashx</label>

    </div>
    <div class="col-xs-12 subsection-header">Deposit</div>

    <div class="form-group col-sm-12 mt-1 ">

        @formHelper.AddToggleBox(Model.DepositAutoApprove, "DepositAutoApprove", "Auto Approve", true)
        @formHelper.AddNumericBox(Model.DepositMatchFreq, "DepositMatchFreq", "Match Frequency", true, true)

    </div>

    <div class="col-xs-12 subsection-header">Withdrawal</div>

    <div class="form-group col-sm-12 mt-1 ">

        @formHelper.AddToggleBox(Model.WithdrawalAutoApprove, "WithdrawalAutoApprove", "Auto Approve", true)
        @formHelper.AddNumericBox(Model.WithdrawalMatchFreq, "WithdrawalMatchFreq", "Match Frequency", true, true)

    </div>

    <div class="col-xs-12 subsection-header">Settings</div>

    @formHelper.AddNumericBox(Model.WalletMinList, "WalletMinList", "Wallet Minimum List", true, true)
    @formHelper.AddNumericBox(Model.WalletMinListApproved, "WalletMinListApproved", "Wallet Minimum List (Approved)", true, true)
    @formHelper.AddToggleBox(Model.ValidateSMSSender, "ValidateSMSSender", "Validate SMS Sender", true)

    <div class="col-xs-12 subsection-header">App Version</div>
    @formHelper.AddNumericBox(Model.PingInterval, "PingInterval", "Ping Interval", true, true)
    @formHelper.AddTextBox(Model.AppVersion, "AppVersion", "App Version", true, true)


    <div class="col-xs-12 subsection-header">Email Notification Setting</div>
    @formHelper.AddToggleBox(Model.SendNotification, "SendNotification", "Send Notification", true)
    @formHelper.AddTextBox(Model.Recipient, "Recipient", "Recipient Seperate by Semicolon (;)", true, true)
    @formHelper.AddNumericBox(Model.IdleInterval, "IdleInterval", "Idle Duration(Interval)", true, true)


    <div class="col-xs-12 subsection-header">Wallet Sender Seperate by Semicolon (;)</div>
    <div id="walletSenderFrm">
        @foreach (KeyValuePair<int, string> item in WalletType)
        {
            string SenderValue = string.Empty;
            if (ShopwalletSenderDict.ContainsKey(item.Key.ToString()))
            {
                SenderValue = ShopwalletSenderDict[item.Key.ToString()].Sender;
            }

            @formHelper.AddTextBox(SenderValue, item.Key.ToString(), item.Value, true, true)

        }
    </div>


    <div class="col-xs-12 subsection-header">Reject Remarks</div>
    <div class="form-group col-12">

        <div class="hr10 visible-xs"></div>
        <button type="button" id="btnAddRemarks" class="btn btn-primary">Add Remark</button>
        <div class="hr10 visible-xs"></div>

    </div>
    <div id="RejectRemarkFrm">
        @foreach (KeyValuePair<string, MGatewayBO.Model.RejectRemarksModel> item in ViewBag.RejectRemark)
        {

            <div class="div-wrapper full-wrap">
                <i class="fa fa-times" data-deleteRemark style="color: red; cursor: pointer;font-size: 25px; padding-top: 10px;"></i>
                <div class="input-wrapper">

                    <input autocomplete="off" class="form-control input-sm   required" data-validate="" id="@item.Key" name="@item.Key" placeholder="" type="text" value="@item.Value.Remark">
                </div>

            </div>


        }
    </div>




    <div class="form-group col-12">
        <div class="text-center">
            <div class="hr10 visible-xs"></div>
            <button type="button" id="btnUpdate" class="btn btn-primary">Save</button>
            <div class="hr10 visible-xs"></div>
        </div>
    </div>
</div>



<script type="text/javascript">

        var UpdateURL = '@Url.Action("UpdateSettings", "GlobalSettings", new { Area = "" })'
        var DeleteRejectRemarkURL = '@Url.Action("DeleteRejectRemark", "GlobalSettings", new { Area = "" })'

        $('#btnUpdate').click(function (e) {
            var WalletSenderList = CollectWalletSenderList();
            var RejectRemarkList = CollectRejectRemarkList();
            var _data = {
            'vm': {
                //$('#chilElement').find('#merchantStatus').is(":checked") ? 1 : 0)
                DepositAutoApprove: ($('#DepositAutoApprove').is(":checked") ? true : false),
                DepositMatchFreq: $('#DepositMatchFreq').val(),
                WithdrawalAutoApprove: ($('#WithdrawalAutoApprove').is(":checked")? true : false),
                WithdrawalMatchFreq: $('#WithdrawalMatchFreq').val(),
                WalletMinList: $('#WalletMinList').val(),
                WalletMinListApproved: $('#WalletMinListApproved').val(),
                AppVersion: $('#AppVersion').val(),
                PingInterval: $('#PingInterval').val(),
                ValidateSMSSender: ($('#ValidateSMSSender').is(":checked") ? true : false),
                Recipient: $('#Recipient').val(),
                IdleInterval: $('#IdleInterval').val(),
                SendNotification: ($('#SendNotification').is(":checked") ? true : false),
            },
            'WalletSenderList': WalletSenderList,
            'RejectRemarksList': RejectRemarkList
        }
        var ajxNew = new _func.ajxNew();

        ajxNew.url = UpdateURL;
        ajxNew.data = _data;

        _func.ajxCall(ajxNew, function (returndata) {
            var data = returndata.returnVal;
            if (returndata) {
                showMessage('Save Successfully!', true);
              //  $('#gdvCampaign').IniJsGrid(data, customItemTemplate);

            };
        });
        })

        $('#btnAddRemarks').click(function (e){

            var elem = $('#RejectRemarkFrm').find('.div-wrapper').first().clone();
            $(elem).find('input').attr('id', '0')
            $(elem).find('input').val('')
            $('#RejectRemarkFrm').append(elem);
        })

        $('#RejectRemarkFrm').on('click', '[data-deleteRemark]', function (e) {
            var ajxNew = new _func.ajxNew();
            var elem = $(this).closest('.full-wrap')
            var remarkID = elem.find('input').attr('id');
            ajxNew.url = DeleteRejectRemarkURL;
            ajxNew.data = { 'ID': remarkID };

            _func.ajxCall(ajxNew, function (returndata) {
                var data = returndata.returnVal;
                if (returndata) {
                    showMessage('Delete Remark Successfully!', true);
                    elem.remove();
                    //  $('#gdvCampaign').IniJsGrid(data, customItemTemplate);

                };
            });
        })

        function CollectWalletSenderList() {
            var WalletSenderList = [];
            $.each($('#walletSenderFrm :input'), function (i, v) {
                var wallettype = $(v).attr('id');
                var walletsender = $(v).val();
                var WalletSender = {
                    WalletType: wallettype,
                    Sender: walletsender
                }

                WalletSenderList.push(WalletSender);
            })

            return WalletSenderList;
        }

        function CollectRejectRemarkList() {
            var RejectRemarkList = [];
            $.each($('#RejectRemarkFrm :input'), function (i, v) {
                var id = $(v).attr('id');
                var remarks = $(v).val();
                var RemarkRemark = {
                    ID: id,
                    Remark: remarks
                }

                RejectRemarkList.push(RemarkRemark);
            })

            return RejectRemarkList;
        }


</script>